services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/dockersamples/labspace-containerized-sdlc

  workspace:
    image: dockersamples/labspace-workspace-node
    ports: !override
      - 8085:8085